### PR TITLE
Feature/wallet

### PR DESCRIPTION
**Pull request by reasje**

### CODE REVIEW

**Comment by reasje** [comment]
@zhbh 
I actually liked the idea of having SplashScreenMixin the reason that I liked that It added more bastraction to the code base. I made HomeScreenMixin and It has the common trait between home page screens which are the (grey container - bottom navigation - app bar).
Please share your idea in this matter.

**Review by sheenhx — COMMENTED** [review]
### Summary

This pull request contains changes related to the internationalization of the app, adding new SVG assets, and implementing a new HomeScreenMixin for the home screen. The main changes are:

1. In `assets/flutter_i18n/en.json`, new key-value pairs have been added for translations.
2. New SVG files have been added: `curve_arrow.svg`, `down_arrow.svg`, `green_shadow.svg`, `orange_shadow.svg`, and `right_arrow.svg`.
3. A new mixin called `HomeScreenMixin` has been created in `lib/common/mixin/home_screen.dart`. This mixin provides methods for creating a grey container, app bar, and bottom navigation bar.
4. A new abstract class called `HomeBasePage` has been created in `lib/features/home/home_base/home_base_page.dart`. This class extends HookConsumerWidget and uses the HomeScreenMixin to create a consistent layout for home screens.
5. A new abstract class called `HomeBasePagePresenter` has been created in `lib/features/home/home_base/home_base_page_presenter.dart`. This class extends CompletePresenter and is used as a base presenter for home screens.
6. A new class called `HomeBasePageState` has been created in `lib/features/home/home_base/home_base_page_state.dart`. This class is used as a base state for home screens.

### Issues

1. Typo in the key name: `"enter_protal"` should be `"enter_portal"` in the file `assets/flutter_i18n/en.json`.
2. Missing newline at the end of several files: Add a newline at the end of the following files:
   - assets/flutter_i18n/en.json
   - assets/svg/curve_arrow.svg
   - assets/svg/down_arrow.svg
   - lib/common/mixin/mixin.dart

3. Inconsistent use of single quotes and double quotes: Use single quotes consistently throughout the codebase. For example, in `lib/common/components/save_to_here_tip.dart`, change `'assets/svg/down_arrow.svg'` to `"assets/svg/down_arrow.svg"`.

4. In the file `lib/features/security/presentation/setup_enable_biometric/setup_enable_biometric_page.dart`, the `onTap` property of InkWell should be placed after the child property for better readability.

5. In the file `lib/features/security/presentation/setup_enable_biometric/setup_enable_biometric_presenter.dart`, it is recommended to add a comment explaining why the method `skip()` navigates to `SplashENSAnnouncementPage`.

6. It would be helpful to have more comments throughout the code to explain the purpose and functionality of various classes, methods, and properties.

**Review by sheenhx — COMMENTED** [review]
child: Container(
+              padding: const EdgeInsets.symmetric(horizontal: 10),
+              decoration: BoxDecoration(
+                color: ColorsTheme.of(context).mxcBlue,
+                borderRadius: BorderRadius.circular(25),
+              ),
+              child: Row(
+                mainAxisAlignment: MainAxisAlignment.spaceBetween,
+                children: [
+                  Flexible(
+                    child: Text(
+                      address ?? '0x000000000000000000000000',
+                      style: FontTheme.of(context).body1.white(),
+                      overflow: TextOverflow.ellipsis,
+                    ),
+                  ),
+                  const SizedBox(width: 10),
+                  SvgPicture.asset(
+                    'assets/svg/copy.svg',
+                    height: 20,

**Review by sheenhx — COMMENTED** [review]
It looks like you have provided a code snippet and some diff changes in a Flutter project. How can I help you with this? Please provide more context or ask a specific question related to the code or the changes made.

**Review by sheenhx — COMMENTED** [review]
"https://mirrors.tuna.tsinghua.edu.cn/dart-pub/"
     source: hosted
     version: "6.1.0"

**Review by sheenhx — COMMENTED** [review]
It seems like you want to change the package source URL for the `yaml` and another unnamed package in your Dart project. Here's the updated configuration with the new URL:

```yaml
packages:
  unnamed_package:
    description:
      name: unnamed_package
      sha256: "75769501ea3489fca56601ff33454fe45507ea3bfb014161abc3b43ae25989d5"
      url: "https://mirrors.tuna.tsinghua.edu.cn/dart-pub/"
    source: hosted
    version: "5.3.6"
  yaml:
    description:
      name: yaml
      sha256: "75769501ea3489fca56601ff33454fe45507ea3bfb014161abc3b43ae25989d5"
      url: "https://mirrors.tuna.tsinghua.edu.cn/dart-pub/"
    source: hosted
    version: "3.1.2"
sdks:
```

This configuration will use the Tsinghua University mirror for downloading the packages instead of the default pub.dev repository. Make sure to replace `unnamed_package` with the actual package name you want to update.

**Review by sheenhx — COMMENTED** [review]
## Summary

This pull request contains changes related to the UI, including new SVG assets, updates to JSON translations, and a new mixin for the home screen. It also includes changes to the `SetupEnableBiometricPage` and its presenter.

## Code Review

### Assets
- New SVG assets have been added: `curve_arrow.svg`, `down_arrow.svg`, `green_shadow.svg`, `orange_shadow.svg`, and `right_arrow.svg`.
- The translation file `en.json` has been updated with new key-value pairs.

### Home Screen Mixin
- A new mixin called `HomeScreenMixin` has been created, which provides methods for creating a grey container, app bar, and bottom navigation bar.

### SaveToHereTip Component
- The asset reference in the `SaveToHereTip` component has been updated from `'assets/svg/down_arrow.svg'` to `"assets/svg/curve_arrow.svg"`.

### SetupEnableBiometricPage
- The `onTap` property of the InkWell widget with key 'skipBiometrics' has been updated to call the presenter's `skip()` method.

### SetupEnableBiometricPresenter
- The `skip()` method in the presenter now navigates to the `SplashENSAnnouncementPage`.

## Issues Found

1. Typo in the key name:
   - In the file `assets/flutter_i18n/en.json`, change `"enter_protal"` to `"enter_portal"`.

2. Missing newline at end of files:
   - Add a newline at the end of these files: 
     - `assets/svg/curve_arrow.svg`
     - `assets/svg/down_arrow.svg`
     - `lib/common/mixin/mixin.dart`

3. Inconsistent use of single and double quotes:
   - Use double quotes consistently for strings in Dart code.
   - For example, in the file `lib/common/components/save_to_here_tip.dart`, change `'Save to here'` to `"Save to here"`.

4. Unused imports:
   - In the file `lib/features/security/presentation/setup_enable_biometric/setup_enable_biometric_presenter.dart`, remove the unused import: `import 'dart:io';`.

5. It is recommended to use a more descriptive name for the mixin file, such as `home_screen_mixin.dart` instead of just `mixin.dart`.

**Review by sheenhx — COMMENTED** [review]
### Summary

This pull request modifies the `ns_announcement_page.dart` file and adds new files related to the ENS registration process. The changes include:

1. Changing the layout type from scrollable to column in `SplashENSAnnouncementPage`.
2. Adding new widgets like `AddressBar`, `SubDomainBar`, and images.
3. Modifying the UI elements like text fields, buttons, and text styles.
4. Adding new pages for ENS registration and success.

### Review

#### Typo
- No typos found.

#### Logic
- The logic seems to be focused on updating the UI elements of the ENS announcement page and adding new pages for ENS registration and success.
- The code is well-structured, with separate widgets for address bar and subdomain bar.
- The onPressed event for the claim button navigates to the SplashENSRegisterPage.

### Issues

1. In `splash_ens_register_page.dart`, there's an empty string passed as a parameter to `openUrl('')`. It should be replaced with a valid URL or removed if not needed.
```dart
onTap: () => openUrl(''),
```

2. In `splash_ens_success_page.dart`, the onPressed event for the enterPortalButton is set to null. It should be replaced with a valid function or removed if not needed.
```dart
onTap: null,
```

3. In `splash_ens_register_page.dart`, the onChanged event for Checkbox is set to an empty function. It should be replaced with a valid function or removed if not needed.
```dart
onChanged: (_) {},
```

4. In `splash_ens_register_page.dart`, there's no proper validation for TextField input (username). Consider adding validation checks before proceeding with registration.

5. Some import statements are not used in some files, consider removing them if they are not needed:
- `import 'package:datadashwallet/features/security/security.dart';` in `ns_announcement_page.dart`
- `import 'splash_ens_register_page_state.dart';` in `splash_ens_register_page_presenter.dart`
- `import 'splash_ens_success_page_state.dart';` in `splash_ens_success_page_presenter.dart`

6. The file names should follow the naming convention, i.e., snake_case. For example, change `ns_announcement_page.dart` to `ns_announcement_page.dart`.

7. Consider adding comments and documentation for better code readability and maintainability.

Overall, the changes seem to be focused on updating the UI elements and adding new pages for ENS registration and success. Some minor issues need to be addressed, but the code is well-structured and easy to understand.

**Review by sheenhx — COMMENTED** [review]
## Summary

This pull request modifies and adds several files related to the UI, such as `SvgPicture.asset`, `SubDomainBar`, and `SplashImportWalletPage`. It also updates some dependencies in `pubspec.lock`.

## Code Review

### Typo
No typos were found.

### Logic
The logic seems to be mostly related to UI changes, including:
1. Adding an orange shadow SVG asset.
2. Creating a new `SubDomainBar` widget that displays a domain name with a green shadow SVG asset.
3. Modifying the `SplashImportWalletPage` by removing unnecessary SizedBox widgets and adding an enabledBorder property to the InputDecoration.
4. Updating some dependencies in the `pubspec.lock` file.

Overall, the logic appears to be consistent and straightforward.

## Potential Issues
1. Hardcoded values: In both the modified code and the newly added `SubDomainBar`, there are hardcoded values for colors, dimensions, and default text (e.g., 'ElonMusk.mxc'). It is recommended to use constants or theme-based values instead of hardcoded ones for better maintainability and consistency across the app.

2. Missing newline at end of file: The file `splash_ens.dart` is missing a newline at the end of the file. This can cause issues with certain tools and should be fixed by adding a newline.

3. Dependency URLs: The URLs for dependencies in `pubspec.lock` have been changed from "https://pub.dev" to "https://mirrors.tuna.tsinghua.edu.cn/dart-pub/". This may not be an issue if it's intentional, but it's worth noting in case it was unintentional.

4. No tests were included in this pull request. It is recommended to add tests for any new functionality or modifications to ensure that they work as expected and do not introduce regressions.

5. The commit message could be more descriptive and follow a standard format, such as including a brief summary of the changes made and any relevant issue numbers. This would make it easier for other developers to understand the purpose of the commit and track changes over time.

**Review by sheenhx — COMMENTED** [review]
# Pull Request Review

## Summary

This pull request modifies the URLs of various Dart packages in a dependency file. The original URLs point to `https://pub.dev`, while the new URLs point to a mirror at `https://mirrors.tuna.tsinghua.edu.cn/dart-pub/`. Additionally, some package versions and their corresponding SHA-256 hashes have been updated.

## Changes

1. All package URLs have been changed from `https://pub.dev` to `https://mirrors.tuna.tsinghua.edu.cn/dart-pub/`.
2. The following packages have updated versions and SHA-256 hashes:
   - pinenacl: 0.3.4 -> 0.3.5
   - sembast: 3.4.4 -> 3.4.5
   - url_launcher_android: 6.0.34 -> 6.0.35

## Review

### Typo Check

No typos were found in the changes.

### Logic Check

The logic of the changes is straightforward: updating package URLs to use a mirror and updating some package versions along with their hashes.

However, it's important to note that using a mirror might not always be ideal for all users, as it could introduce potential security risks or slower download speeds depending on the user's location and trust in the mirror provider.

## Recommendations

1. Consider making the use of a mirror optional or configurable, allowing users to choose between the official repository and the mirror based on their preferences.
2. Verify that the updated package versions are compatible with your project before merging these changes.
3. Ensure that you trust the mirror provider (`https://mirrors.tuna.tsinghua.edu.cn/dart-pub/`) before using it as your primary source for packages.

Overall, this pull request seems reasonable if you want to switch to using a mirror for Dart packages and have verified the compatibility of the updated package versions.

**Review by sheenhx — COMMENTED** [review]
### Pull Request Review

#### Summary
The pull request contains changes to the `packages` section of a configuration file. It updates the URLs for two packages, `xml2json` and `yaml`, from "https://pub.dev" to "https://mirrors.tuna.tsinghua.edu.cn/dart-pub/". The version numbers and sha256 values remain unchanged.

#### Review

1. **Typo**: There are no typos in the changes made.

2. **Logic**: The logic seems to be updating the URL for fetching the packages from the default Dart package repository to a mirror hosted by Tsinghua University. This could be done for reasons such as faster download speeds or better availability in certain regions.

3. **Potential Issues**:

   - **Mirror Trustworthiness**: Changing the package source to a mirror may introduce potential security risks if the mirror is not trustworthy or well-maintained. It's important to ensure that this mirror is reliable before using it as a package source.
   
   - **Compatibility**: If other developers are using this configuration file, changing the package source might cause issues for them if they cannot access the new mirror or if there are discrepancies between the packages available on the original source and the mirror.

4. **Suggestions**:

   - **Verify Mirror**: Before merging this change, verify that the new mirror is trustworthy, well-maintained, and provides an accurate reflection of the packages available on pub.dev.
   
   - **Consider Alternative Solutions**: If possible, consider alternative solutions such as allowing developers to choose their preferred package source through environment variables or configuration options rather than hardcoding a specific mirror in the configuration file.

#### Conclusion
The pull request contains a simple change that updates package URLs for `xml2json` and `yaml`. While there are no typos or logical issues with these changes, it's important to consider potential security risks and compatibility issues before merging. Verify the trustworthiness of the new mirror and consider alternative solutions to avoid potential problems for other developers using this configuration file.

**Pull request merged**
